remove 'from . import ...' imports from wc_lang/__init__.py so that SchemaModule.import_module_for_migration() can import wc_lang without 'ImportError: cannot import name'